environment: production
port: 3000

image:
  repo: web3f/polkadot-watcher
  tag: v0.10.0

config:
  endpoint: "wss://cc3-3.kusama.network"
  port: 3000
  logLevel: info
  subscribe:
    producers: []

serviceMonitor:
  labels:
    group: w3f
    release: prometheus-operator

prometheusRules:
  labels:
    app: w3f

networkId: kusama

origin: cluster

resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "100m"
    memory: "500Mi"
